/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#343537",
        "outline-variant": "#43474d",
        "on-surface": "#e3e2e4",
        "error": "#ffb4ab",
        "on-primary-container": "#6d849e",
        "surface-dim": "#121315",
        "secondary": "#ffb4ab",
        "on-primary": "#1b3249",
        "surface-container-high": "#292a2c",
        "on-secondary-container": "#ffd7d2",
        "on-error": "#690005",
        "inverse-surface": "#e3e2e4",
        "secondary-fixed-dim": "#ffb4ab",
        "secondary-fixed": "#ffdad6",
        "inverse-on-surface": "#303032",
        "background": "#121315",
        "on-background": "#e3e2e4",
        "tertiary": "#d9c900",
        "on-surface-variant": "#c3c6cd",
        "surface-bright": "#38393b",
        "on-secondary-fixed-variant": "#93000b",
        "tertiary-fixed": "#f8e600",
        "secondary-container": "#c90014",
        "primary-container": "#001a30",
        "on-primary-fixed": "#021d33",
        "primary-fixed-dim": "#b1c9e6",
        "primary": "#b1c9e6",
        "on-tertiary": "#363100",
        "on-tertiary-fixed": "#1f1c00",
        "on-tertiary-fixed-variant": "#4e4800",
        "on-tertiary-container": "#464000",
        "outline": "#8d9197",
        "on-primary-fixed-variant": "#324961",
        "on-secondary-fixed": "#410002",
        "surface-tint": "#b1c9e6",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0d0e10",
        "tertiary-container": "#bcad00",
        "surface": "#121315",
        "surface-container-highest": "#343537",
        "inverse-primary": "#4a6079",
        "surface-container": "#1f2021",
        "primary-fixed": "#d0e4ff",
        "on-secondary": "#690005",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#d9c900",
        "surface-container-low": "#1b1c1d",
        "card-navy": "#0A1F33",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "max-width": "1440px",
        "margin-desktop": "64px",
        unit: "4px",
        "margin-mobile": "16px",
      },
      maxWidth: {
        layout: "1440px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "label-pixel": ["JetBrains Mono", "monospace"],
        "display-lg": ["Sora", "sans-serif"],
        code: ["JetBrains Mono", "monospace"],
        "headline-lg": ["Sora", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-pixel": ["12px", { lineHeight: "1.0", fontWeight: "700" }],
        "display-lg": [
          "72px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.04em",
            fontWeight: "800",
          },
        ],
        code: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": [
          "40px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
      },
    },
  },
  plugins: [],
};
